name: CI/CD for Docker Container (Self-Deployment)

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t social-accountability:latest .
        docker images  # Verify the image exists

    # Step 3: Deploy the Docker container locally
    - name: Deploy container
      run: |
        # Stop and remove the existing container if running
        docker stop social-accountability || true
        docker rm social-accountability || true

        # Run the new container
        docker run -d --name social-accountability -p 8002:8002 social-accountability:latest

